/**
 * CECS 277-07
 * Project 4 - Project File I/O
 * Professor Mimi Opkins
 * @author Ryan Ignasiak, Tina Vu, Matthew Chen
 * 10/21/20
 */
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.NoSuchElementException;
import java.util.Scanner;

/**
 * Reads information from command line argument, then uses that file to create new files based on Sales object
 * service type
 * */
public class Main2 {
    /**
     * Default constructor for writeToFiles class*/
    public Main2() {
    }

    /**
     * Reads lines from the input file passed into the command line
     * @param in the Scanner object
     * @return the Sales object
     * */
    private static Sales readSaleEntry(Scanner in) {
        String inputLine = in.nextLine();
        Scanner lineScan = new Scanner(inputLine);
        lineScan.useDelimiter(";");
        String name = lineScan.next();
        String service = lineScan.next();
        double amount = lineScan.nextDouble();
        String date = lineScan.next();
        return new Sales(name, service, amount, date);
    }

    /**
     * Fills an ArrayList with Sales objects which are generated by the readSaleEntry method
     * @param filename the file name from which sales entries are read
     * @return the ArrayList of sales
     * */
    private static ArrayList<Sales> readSalesFile(String filename) throws FileNotFoundException {
        ArrayList<Sales> sales = new ArrayList();
        if (filename != null) {
            Scanner infile = new Scanner(new FileReader(filename));
            try {
                while(infile.hasNext()) {
                    sales.add(readSaleEntry(infile));
                }
            } catch (Throwable var6) {
                try {
                    infile.close();
                } catch (Throwable var5) {
                    var6.addSuppressed(var5);
                }
                throw var6;
            }
            infile.close();
        }
        return sales;
    }

    /**
     * Prints the sale data to an output file
     * @param out the file to print the data to
     * @param sale the Sales object*/
    private static void writeSale(PrintWriter out, Sales sale) {
        out.print(sale.getName());
        out.print(";");
        out.print(sale.getServiceCategory());
        out.print(";");
        out.print(sale.getAmount());
        out.print(";");
        out.print(sale.getDate());
        out.println();
    }

    public static void main(String[] args) throws FileNotFoundException {
        String filename = args[0];
        String eventType = "";
        PrintWriter event = new PrintWriter(new FileOutputStream("empty.txt", true));

        try {
            ArrayList<Sales> sales = readSalesFile(filename);
            Iterator var5 = sales.iterator();

            while(var5.hasNext()) {

                Sales s = (Sales)var5.next();
                eventType = s.getServiceCategory()+".txt";

                if (!event.equals(eventType)) {
                    event = new PrintWriter(new FileOutputStream(eventType, true));
                }

                System.out.println(s);
                writeSale(event, s);
                event.close();
            }
        } catch (FileNotFoundException var7) {
            System.out.println("File not found!");
        } catch (NoSuchElementException var8) {
            System.out.println("File format not valid.");
        }
    }
}